#pragma once

#include "gsw.h"
#include "pir.h"
#include "bv_keyswitch.h"
#include "aligned_allocator.h"
#include <map>
#include <sstream>
#include <unordered_map>

class PirServer {
public:
  PirServer(const PirParams &pir_params);
  ~PirServer();

  /**
   * Generate random data for the server database and directly set the database.
   * It pushes the data to the database in chunks.
   */
  void gen_data(const std::vector<size_t>& record_indices = {});

  // Given the client id and a packed client query, this function first unpacks the query, then returns the retrieved encrypted result.
  RlweCt make_query(const size_t client_id, RlweCt &query);

  // DoubleStateless query path: no server-resident keys. The client ships a real
  // BFV root and fresh RGSW selectors; the server expands the first dimension
  // with DMux, then runs the subsequent dimensions with the supplied selectors
  // directly (no query_to_gsw). first_dim_query: the real BFV one-hot the DMux
  // starts from (e.g. a single BFV(1), or a 2^m one-hot resolving the top m
  // bits). first_dim_selectors: one RGSW(bit) per remaining first-dim tree level.
  // other_dim_selectors: num_dims-1 RGSW(bit), ordered as get_query_indices()[1..].
  RlweCt make_query_dmux(std::vector<RlweCt> first_dim_query,
                         const std::vector<GSWCt> &first_dim_selectors,
                         std::vector<GSWCt> &other_dim_selectors);
  // return the number of bits needed to represent the server reponse
  size_t save_resp_to_stream(const RlweCt &response, std::stringstream &resp_stream);
  void set_client_bv_galois_key(const size_t client_id, bvks::BvGaloisKeys bv_keys);
  void set_client_gsw_key(const size_t client_id, GSWCt gsw_key);

  /**
  Asking the server to return the original plaintext (before NTT transformation) at the given index.
  This is not doing PIR. So this reveals the index to the server. This is
  only for testing purposes.
  */
  RlwePt direct_get_original_plaintext(const size_t index) const;


  // high level: homomorphic matrix vector multiplication between plaintext database and query ciphertext
  // input selection_vector should stay in coefficient form.
  // output will be in coefficient form.
  std::vector<RlweCt> evaluate_first_dim(std::vector<RlweCt> &selection_vector);

  /**
   * @brief A clever way to evaluate the external product for second to last dimensions.
   *
   * @param intermediate_db The BFV ciphertexts after the first dimension evaluation.
   * @param selectors A vector of RGSW(b) ciphertexts, where b \in {0, 1}. 0 to get the first half of the result, 1 to get the second half.
   */
  RlweCt evaluate_other_dim(std::vector<RlweCt> &intermediate_db, std::vector<GSWCt> &selectors);

  // compute x = b * (y - x) + x
  void ext_prod_mux(RlweCt &x, RlweCt &y, GSWCt &selection_cipher, RlweCt &result);


  friend class PirTest;

private:
  size_t num_pt_;
  std::map<size_t, bvks::BvGaloisKeys> client_bv_galois_keys_;
  std::map<size_t, GSWCt> client_gsw_keys_;
  std::unordered_map<size_t, RlwePt> recorded_pts_; // pre-NTT plaintexts for test verification
  std::unique_ptr<db_coeff_t[], AlignedDeleter<db_coeff_t>> db_aligned_; // aligned database for fast first dim
  std::vector<inter_coeff_t> inter_res_; // intermediate result vector for fst dim

  // Composite-mod first-dim path (q = q1 * q2). When DBConsts::CompositeFirstDim
  // is true these replace db_aligned_ + inter_res_: the DB is split into two
  // u32 arrays (one per RNS limb), and the matmul writes into two u64 buffers
  // which are CRT-composed in inter_to_cts_composite.
  std::unique_ptr<uint32_t[], AlignedDeleter<uint32_t>> db_lo_;
  std::unique_ptr<uint32_t[], AlignedDeleter<uint32_t>> db_hi_;
  std::vector<uint64_t> inter_res_lo_;
  std::vector<uint64_t> inter_res_hi_;
  PirParams pir_params_;
  GSWEval key_gsw_;
  GSWEval data_gsw_;

  // we apply new techniques to avoid trivial splits on zero ciphertexts.
  // Notice that a large portion of the query is zero, and they are generated by
  // splitting some zero ciphertexts. Trivial split are the ones that split the
  // zero ciphertexts into two zero ciphertexts. However, to do this, we must
  // make sure that all the first dimension is in the same expansion sub-tree.
  // The expand query used in Cheetah is not suitable for this, though we don't
  // need special permutation for packing when using it.
  std::vector<RlweCt> fast_expand_qry(size_t client_id, RlweCt &ciphertext) const;

  std::vector<RlweCt> full_expand_qry(size_t client_id, RlweCt &ciphertext) const;

  // DMux-based query expansion: an alternative to fast_expand_qry's Galois
  // route that uses only external products. Each selector level splits every
  // query ciphertext c with an RGSW selector C via
  //   DMux(c, C) = (c - EP(C, c), EP(C, c)).
  // The output length is query.size() << selectors.size(). When the input query
  // is one-hot (exactly one BFV(1), the rest BFV(0)), so is the output: the lone
  // "1" sits at the index whose remaining low bits are encoded MSB-first by the
  // selector bits.
  //
  // `query` is the starting set of ciphertexts, in coefficient form, K-limb: a
  // real client BFV(0)/BFV(1) one-hot vector of size 2^m. The client resolves
  // the top m bits by sending 2^m small BFV ciphertexts, and the remaining h-m
  // selectors finish the tree. The BFV ciphertexts must be real (noisy)
  // encryptions so BFV(0) and BFV(1) are indistinguishable.
  // `selectors` must be fresh RGSW(bit) under the data-gsw gadget of length
  // gsw_l (see PirClient::generate_dmux_selectors); gsw_l must match the
  // client's so the per-level decomposition lines up with the selectors.
  std::vector<RlweCt> dmux_expand_qry(std::vector<RlweCt> query,
                                      const std::vector<GSWCt> &selectors,
                                      const size_t gsw_l);

  // Convert the first-dim matmul output `inter_res` into per-ciphertext form.
  // Two responsibilities:
  //   1. Layout transpose. mat_mat writes coeff-major:
  //        inter_res[level][i][p]   for i ∈ [0, other_dim_sz), p ∈ {0,1}
  //      with stride `other_dim_sz * 2` between coefficient levels. The
  //      per-ciphertext layout we want is poly-contiguous:
  //        cts[i].c{p}[level]
  //   2. NTT inverse on each polynomial (database is in NTT form).
  //
  // Assumes mat_mat already produced values < q at every output position
  // (chunked / AVX-512 paths both reduce per output write), so no `% q`
  // is performed here.
  void inter_to_cts(std::vector<RlweCt> &result, const inter_coeff_t *__restrict inter_res);

  // Fill the intermediate_db_ with some ciphertext. We just need to allocate the memory.
  void fill_inter_res();

  void prep_query(std::vector<RlweCt> &fst_dim_query, std::vector<db_coeff_t>& query_data);

  // Composite-mod variant: splits each NTT query coefficient into (mod q1,
  // mod q2) u32 buffers. Inputs are already NTT-transformed under q = q1*q2.
  void prep_query_composite(const std::vector<RlweCt> &fst_dim_query,
                            uint32_t *query_lo, uint32_t *query_hi);

  // Composite-mod variant of inter_to_cts: reads two per-limb u64 buffers,
  // CRT-composes each coefficient back to mod q = q1*q2, then runs a single
  // INTT mod q.
  void inter_to_cts_composite(std::vector<RlweCt> &result,
                              const uint64_t *inter_lo,
                              const uint64_t *inter_hi);

  // customized modulus switch for single mod RlweCt. (Not RNS modulus)
  // The goal is to halve the size of the ciphertext.
  void mod_switch_inplace(RlweCt &ciphertext, const uint64_t small_q);

};
