#pragma once

#include "gsw_eval.h"
#include "pir.h"
#include "bv_keyswitch.h"
#include "aligned_allocator.h"
#include <optional>
#include <unordered_map>

// typedef std::vector<std::optional<seal::Plaintext>> DatabaseChunk;  // 256 plaintexts
typedef std::unique_ptr<std::optional<seal::Plaintext>[]> DatabaseChunk;  // Heap allocation for N_1 plaintexts
typedef std::unique_ptr<std::optional<seal::Plaintext>[]> Database;       // One consecutive huge vector for the entire database on heap

class PirServer {
public:
  PirServer(const PirParams &pir_params);
  ~PirServer();

  /**
   * Generate random data for the server database and directly set the database.
   * It pushes the data to the database in chunks.
   */
  void gen_data(const std::vector<size_t>& record_indices = {});

  // Given the client id and a packed client query, this function first unpacks the query, then returns the retrieved encrypted result.
  // use_bv: if true, use BV key-switching for expansion; if false, use GHS (SEAL galois keys).
  seal::Ciphertext make_query(const size_t client_id, seal::Ciphertext &query, seal::Decryptor &decryptor, bool use_bv = true);
  // return the number of bits needed to represent the server reponse
  size_t save_resp_to_stream(const seal::Ciphertext &response, std::stringstream &resp_stream);
  void set_client_galois_key(const size_t client_id, std::stringstream &gsw_stream);
  void set_client_bv_galois_key(const size_t client_id, bvks::BvGaloisKeys bv_keys);
  void set_client_gsw_key(const size_t client_id, GSWCiphertext gsw_key);

  /**
  Asking the server to return the original plaintext (before NTT transformation) at the given index.
  This is not doing PIR. So this reveals the index to the server. This is
  only for testing purposes.
  */
  seal::Plaintext direct_get_original_plaintext(const size_t index) const;


  // high level: homomorphic matrix vector multiplication between plaintext database and query ciphertext
  // input selection_vector should stay in coefficient form.
  // output will be in coefficient form.
  std::vector<seal::Ciphertext> evaluate_first_dim(std::vector<seal::Ciphertext> &selection_vector);

  /**
   * @brief A clever way to evaluate the external product for second to last dimensions. 
   * 
   * @param intermediate_db The BFV ciphertexts after the first dimension evaluation.
   * @param selectors A vector of RGSW(b) ciphertexts, where b \in {0, 1}. 0 to get the first half of the result, 1 to get the second half.
   */
  seal::Ciphertext evaluate_other_dim(std::vector<seal::Ciphertext> &intermediate_db, std::vector<GSWCiphertext> &selectors);

  // compute x = b * (y - x) + x
  void ext_prod_mux(seal::Ciphertext &x, seal::Ciphertext &y, GSWCiphertext &selection_cipher, seal::Ciphertext &result);


  friend class PirTest;

private:
  size_t num_pt_;
  seal::SEALContext context_;
  seal::Evaluator evaluator_;
  std::map<size_t, seal::GaloisKeys> client_galois_keys_;
  std::map<size_t, bvks::BvGaloisKeys> client_bv_galois_keys_;
  std::map<size_t, GSWCiphertext> client_gsw_keys_;
  std::unordered_map<size_t, seal::Plaintext> recorded_pts_; // pre-NTT plaintexts for test verification
  std::unique_ptr<db_coeff_t[], AlignedDeleter<db_coeff_t>> db_aligned_; // aligned database for fast first dim
  std::vector<inter_coeff_t> inter_res_; // intermediate result vector for fst dim
  PirParams pir_params_;
  GSWEval key_gsw_;
  GSWEval data_gsw_;

  // Expands the query BFV ciphertext into a vector of BFV ciphertexts,
  // where the first DBConsts::MaxFstDim many ciphertexts is the first dimension query,
  // and the rest will be used to reconstruct the RGSW ciphertexts for the other dimensions.
  std::vector<seal::Ciphertext> expand_query(size_t client_id, seal::Ciphertext &ciphertext) const;

  // we apply new techniques to avoid trivial splits on zero ciphertexts.
  // Notice that a large portion of the query is zero, and they are generated by
  // splitting some zero ciphertexts. Trivial split are the ones that split the
  // zero ciphertexts into two zero ciphertexts. However, to do this, we must
  // make sure that all the first dimension is in the same expansion sub-tree.
  // The expand query used in Cheetah is not suitable for this, though we don't
  // need special permutation for packing when using it.
  std::vector<seal::Ciphertext> fast_expand_qry(size_t client_id, seal::Ciphertext &ciphertext) const;

  // This is a helper for evaluate the first dimension. 
  // Instead of doing a mod operation after every addition and multiplication during the matrix multiplication,
  // we delay the mod operation until the end. We also use barret reduction for the mod operation.
  void delay_modulus(std::vector<seal::Ciphertext> &result, const inter_coeff_t *__restrict inter_res);
  

  // Fill the intermediate_db_ with some ciphertext. We just need to allocate the memory.
  void fill_inter_res();

  void prep_query(const std::vector<seal::Ciphertext> &fst_dim_query, std::vector<db_coeff_t>& query_data);

  // customized modulus switch for single mod seal::Ciphertext. (Not RNS modulus)
  // The goal is to halve the size of the ciphertext.
  void mod_switch_inplace(seal::Ciphertext &ciphertext, const uint64_t small_q);

};
